name: 'Run Tests'
description: 'Run Rust tests and extract results'

inputs:
  features:
    description: 'Features to enable for tests'
    required: false
    default: '--all-features'
  rust_backtrace:
    description: 'RUST_BACKTRACE value'
    required: false
    default: '1'

outputs:
  passed:
    description: 'Number of tests passed'
  failed:
    description: 'Number of tests failed'
  ignored:
    description: 'Number of tests ignored'
  summary:
    description: 'Test result summary line'

runs:
  using: 'composite'
  steps:
    - name: Run tests
      id: test
      shell: bash
      run: |
        cargo test ${{ inputs.features }} --verbose -- --nocapture 2>&1 | tee test-output.txt
        TEST_RESULT=$?
        
        # Extract test summary - find the test result with the most tests (main test suite)
        if grep -q "test result:" test-output.txt; then
          # Find the test result line with the highest number of passed tests
          # This handles multiple test suites (lib, doc, integration, etc.)
          MAX_PASSED=0
          TEST_SUMMARY=""
          
          while IFS= read -r line; do
            # Extract passed count from this line
            LINE_PASSED=$(echo "$line" | grep -oE '[0-9]+ passed' | grep -oE '[0-9]+' | head -1)
            if [ -n "$LINE_PASSED" ] && [ "$LINE_PASSED" -gt "$MAX_PASSED" ]; then
              MAX_PASSED=$LINE_PASSED
              TEST_SUMMARY="$line"
            fi
          done < <(grep "test result:" test-output.txt)
          
          # If we found a test result, extract all counts from it
          if [ -n "$TEST_SUMMARY" ]; then
            PASSED=$(echo "$TEST_SUMMARY" | grep -oE '[0-9]+ passed' | grep -oE '[0-9]+' | head -1)
            FAILED=$(echo "$TEST_SUMMARY" | grep -oE '[0-9]+ failed' | grep -oE '[0-9]+' | head -1)
            IGNORED=$(echo "$TEST_SUMMARY" | grep -oE '[0-9]+ ignored' | grep -oE '[0-9]+' | head -1)
            
            # Ensure we have valid numbers
            [ -z "$PASSED" ] && PASSED="0"
            [ -z "$FAILED" ] && FAILED="0"
            [ -z "$IGNORED" ] && IGNORED="0"
          else
            # Fallback: use the first test result line
            TEST_SUMMARY=$(grep "test result:" test-output.txt | head -1)
            PASSED="0"
            FAILED="0"
            IGNORED="0"
          fi
          
          echo "summary=$TEST_SUMMARY" >> $GITHUB_OUTPUT
          echo "passed=$PASSED" >> $GITHUB_OUTPUT
          echo "failed=$FAILED" >> $GITHUB_OUTPUT
          echo "ignored=$IGNORED" >> $GITHUB_OUTPUT
        fi
        
        exit $TEST_RESULT
      env:
        RUST_BACKTRACE: ${{ inputs.rust_backtrace }}

    - name: Upload test output
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-output
        path: test-output.txt
        retention-days: 7
