name: 'Run Tests'
description: 'Run Rust tests and extract results'

inputs:
  features:
    description: 'Features to enable for tests'
    required: false
    default: '--all-features'
  rust_backtrace:
    description: 'RUST_BACKTRACE value'
    required: false
    default: '1'

outputs:
  passed:
    description: 'Number of tests passed'
  failed:
    description: 'Number of tests failed'
  ignored:
    description: 'Number of tests ignored'
  summary:
    description: 'Test result summary line'

runs:
  using: 'composite'
  steps:
    - name: Run tests
      id: test
      shell: bash
      run: |
        cargo test ${{ inputs.features }} --verbose -- --nocapture 2>&1 | tee test-output.txt
        TEST_RESULT=$?
        
        # Extract test summary - get all test result lines and sum them up
        if grep -q "test result:" test-output.txt; then
          # Get the last test result line (usually the aggregate)
          TEST_SUMMARY=$(grep "test result:" test-output.txt | tail -1)
          echo "summary=$TEST_SUMMARY" >> $GITHUB_OUTPUT
          
          # Extract counts using grep and awk for more reliable parsing
          # Format: "test result: ok. 78 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out;"
          PASSED=$(echo "$TEST_SUMMARY" | grep -oE '[0-9]+ passed' | grep -oE '[0-9]+' | head -1)
          FAILED=$(echo "$TEST_SUMMARY" | grep -oE '[0-9]+ failed' | grep -oE '[0-9]+' | head -1)
          IGNORED=$(echo "$TEST_SUMMARY" | grep -oE '[0-9]+ ignored' | grep -oE '[0-9]+' | head -1)
          
          # Ensure we have valid numbers
          [ -z "$PASSED" ] && PASSED="0"
          [ -z "$FAILED" ] && FAILED="0"
          [ -z "$IGNORED" ] && IGNORED="0"
          
          echo "passed=$PASSED" >> $GITHUB_OUTPUT
          echo "failed=$FAILED" >> $GITHUB_OUTPUT
          echo "ignored=$IGNORED" >> $GITHUB_OUTPUT
        fi
        
        exit $TEST_RESULT
      env:
        RUST_BACKTRACE: ${{ inputs.rust_backtrace }}

    - name: Upload test output
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-output
        path: test-output.txt
        retention-days: 7
